### ISSUE TITLE
Incompatiblity with pymarkdown attr_list extension

### ISSUE THREAD

**Issue by wojciechczerniak** [theskumar/autolink-references-mkdocs-plugin#1]
`attr_list` extensions is used by multiple mkdocs themes, and possibly incompatible with this plugin

Let's say we want to link to header anchors:

```yaml
  - autolink_references:
      autolinks:
          - reference_prefix: F-
            target_url: /features#F-<num>
```

And those anchors we want to add manually with `attr_list` extension:

```md
## Feature 1 { #F-001 .class-feature }

Lorem ipsum ...

## Feature 2 { #F-002 .class-feature }

Lorem ipsum ...
```

This plugin will break the `attr_list` tag by changing it to something like:

```
## Feature 2 { #[F-002](/features#F-002) .class-feature }
```

And as a result:
- `attr_list` will not be recognized and will be injected into the content creating ugly "Feature 2 { F-002 " header
- header ID will be auto-generated from title as `#feature-` and therefore, auto-links will not work

Please, add a feature to skip `attr_list` tags when `attr_list` is enabled.

Link to `attr_list` extension and syntax: https://python-markdown.github.io/extensions/attr_list/

----
Thanks for your work and this plugin, very useful.
