### ISSUE TITLE
Conflicts with some documents when using GitHub hash sign prefixed issues

### ISSUE THREAD

**Issue by redtide** [theskumar/autolink-references-mkdocs-plugin#7]
`mkdocs.yml`:
```yml
  autolink_references:
    autolinks:
      - reference_prefix: '#'
        target_url: "https://github.com/USER/PROJECT/issues/<num>"
```
which it's quite intuitive that this turns on a lot of conflicts.
So the questions are:
- is there an alternative to avoid problems with anything in the docs? I can't use the form `<user>/<project>#<num>`
- can be applied a filter for specific folders/files where it is enabled to work?
  E.g. I need it only to work in `docs/news/` directory, where I mention the issues only in the application' release posts:

```yml
  autolink_references:
    autolinks:
      - sources:
        - "docs/PROJECT1/news/"
        - "docs/PROJECT1/changes.md"
        target_url: "https://github.com/USER/PROJECT1/issues/<num>"
        reference_prefix: '#'
      - sources:
        - "docs/PROJECT2/news/"
        - "docs/PROJECT2/changes.md"
        target_url: "https://github.com/USER/PROJECT2/issues/<num>"
        reference_prefix: '#'
```
